// Browser-safe configuration only.
// NEVER place SUPABASE_SERVICE_ROLE_KEY or PAYMONGO_SECRET_KEY here.
export const CONFIG = {
  SUPABASE_URL: "https://YOUR_PROJECT.supabase.co",
  SUPABASE_ANON_KEY: "YOUR_SUPABASE_ANON_KEY",
  STORE_NAME: "THRIFTHEADS®",
  CURRENCY: "PHP",
  SHIPPING_FEE: 150
};
